### ISSUE TITLE
Cannot update mailing template

### ISSUE THREAD

**Issue by rkovarik** [Silverpop/engage-api-client#25]
Reason: SaveMailingHeader#mailingId annotation has wrong value
@XStreamAlias("MailingId")
private Long mailingId;

Should be:
@XStreamAlias("MailingID")
private Long mailingId;

One can create new mailing template but not update it, since MailingID is required for this operation.

**Comment by ChrisCurtin** [comment]
Same change was made a part of the next release. Sorry it took so long to come back to this.
