### ISSUE TITLE
Improve ScheduleMailing

### ISSUE THREAD

**Issue by rkovarik** [Silverpop/engage-api-client#35]
Some elements are not supported by current implementation:
SEND_TIME_OPTIMIZATION
WA_MAILINGLEVEL_CODE
SUPPRESSION_LISTS
PARENT_FOLDER_PATH
CREATE_PARENT_FOLD ER
CUSTOM_OPT_OUT
SUPPRESSION_LIST_ID

**Comment by PeterJLyons** [comment]
I'll look into this, shouldn't be too hard. on the to-do list.

**Comment by PeterJLyons** [comment]
Updated and in lastest pull request against the develop branch.

**Comment by ChrisCurtin** [comment]
Completed. Merged into develop
