### ISSUE TITLE
Implement DoubleOptInRecipient command

### ISSUE THREAD

**Issue by rkovarik** [Silverpop/engage-api-client#37]

**Comment by PeterJLyons** [comment]
Working on this - successfully pings the server but returns an error that is thrown by the api and not by the java client, so as far as I know it works. Can't 100% say it works until I get a successful result and not just different types of failures returned by the server it's pinging.

**Comment by rkovarik** [comment]
Works on my side as follows:
1. AddRecipientCommand (against a double opt-in database)
2. DoubleOptInRecipientCommand (success)
Calling the 2. again when the recipient is already opted in results in: 
Error Saving Recipient: null

**Comment by ChrisCurtin** [comment]
Completed. Merged into develop
