### ISSUE TITLE
Implement AddListColumn

### ISSUE THREAD

**Issue by rkovarik** [Silverpop/engage-api-client#38]

**Comment by ChrisCurtin** [comment]
We're working on adding all the APIs not currently supported in this library. Hope to evaluate/accept the outstanding pull requests this week (by 10/16) and start adding our changes.

**Comment by PeterJLyons** [comment]
made a pull request against development on 10/13/2015 with the changes I've made so far.

**Comment by PeterJLyons** [comment]
AddListColumn has been implemented and works as of the latest pull request put into Chris's development branch.

**Comment by ChrisCurtin** [comment]
Peter meant the develop branch in this project.
