### ISSUE TITLE
engage-api-client and UTF-8 requests

### ISSUE THREAD

**Issue by bdbavis** [Silverpop/engage-api-client#52]
It seems that the API fails to handle Cyrillic  letters when sending them to Engage.

**Comment by smitchelus** [comment]
@bdbavis, could you provide more detail? Some examples of the calls you are making?

**Comment by bdbavis** [comment]
@smitchelus 
I'm using AddRecipientCommand() to add new contact to my DB on Silverpop,
One of the columns that i'm sending on my request is the name of the customer.
When the name contain Cyrillic letters like чийнбд it appears on DB as ?????.
I think that the problem is that the client API does not use UTF-8 when sending the request to Engage.

**Comment by smitchelus** [comment]
@bdbavis, if you need to use an encoding other than your JVM's default encoding then you would need to wrap the API command in an [EncodedApiCommand](https://github.com/Silverpop/engage-api-client/blob/11ae36cb0512cd32d0634d83c38c1af6d4f09307/src/main/java/com/silverpop/api/client/command/EncodedApiCommand.java) and specify the desired encoding in there. 

For example:
        ApiCommand command = commandFactory.createSaveMailingCommand(mailing);
        EncodedApiCommand encodedCommand = new EncodedApiCommand(command, "UTF-8");

**Comment by bdbavis** [comment]
@smitchelus 
thanks... you helped me a lot :-)
