### ISSUE TITLE
Service Operation Identification Failure

### ISSUE THREAD

**Issue by akho912** [Silverpop/engage-api-client#60]
HI,

I found this site and downloaded to test.  Ran OAuthClientDemo and got this error.
INFO: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> 
     <soap:Body>
         <soap:Fault>
            <faultcode>soap:Client</faultcode>
            <faultstring>Service Operation Identification Failure</faultstring>
            <faultactor></faultactor>
            <detail>
                  <source>
                    <errorcode>26110</errorcode>
                    <trace>
                        Fault Name: ServiceOperationIdentificationFailure
                        Error Type: Default
                        Description: Service Operation Identification Failure
                        Service: EngageApiService
                        Endpoint: EngageSoapApiClientService
                        Operation (Client):
                    </trace>
                </source> 
            </detail>
        </soap:Fault>
    </soap:Body>
</soap:Envelope>

Exception in thread "main" com.thoughtworks.xstream.mapper.CannotResolveClassException: soap:Envelope
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)

What am I missing?

Thanks!

**Comment by ChrisCurtin** [comment]
Please provide more details for us
- what instance are you trying to connect to?
- what is the body you are trying to send?
- you've provide the oauth credentials you got from Engage/marketing cloud right?

The error suggests something in the body is wrong as we try to figure out the request.
