### ISSUE TITLE
Implement OAuth Support

### ISSUE THREAD

**Issue by smitchelus** [Silverpop/engage-api-client#8]

**Comment by rkovarik** [comment]
Another good reason to go for it: 
"The response, as stated above, provides you with an Access Token which has a set lifetime of 4 hours."
I'm just working on it.

**Comment by ChrisCurtin** [comment]
I'm merged rkovarik's changes into a private branch and we'll be testing next week.

**Comment by ChrisCurtin** [comment]
rkovarik's changes were merged into develop on 11/4/2015.
